remote_theme: matthiaslischka/jekyll-uno

# Site settings
title: 'LHTML5 Spec'
description: 'Official LHTML5 Specification'
url: ''

author:
  name: 'Matthew Heroux'
  github_username: hxtree

kramdown:
  # use Github Flavored Markdown
  input: GFM
  # do not replace newlines by <br>s
  hard_wrap: false

plugins:
  - jekyll-paginate
  - jekyll-remote-theme
  - jekyll-include-cache

exclude: ['README.md', 'Gemfile', 'Gemfile.lock', '.travis.yml', 'vendor']